spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=student-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://student-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/students/**

spring.cloud.gateway.server.webmvc.routes[1].id=course-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://course-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/courses/**

spring.cloud.gateway.server.webmvc.routes[2].id=enrollment-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://enrollment-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/enrollments/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/